<?php 
  /**
  * @file
  * com_gar_blocks.module
  */

  function com_gar_blocks_block_info() {
  $blocks = array();
  
  $blocks['user_forum_posts'] = array(
    'info' => 'User Forum Posts',
    'cache' => DRUPAL_NO_CACHE,
    
  );
  $blocks['user_profile'] = array(
    'info' => 'User Profile',
    'cache' => DRUPAL_NO_CACHE, // default
  ); 
   
  $blocks['users_list'] = array(
    'info' => 'Users List',
    'cache' => DRUPAL_NO_CACHE, // default
  ); 
    
  $blocks['contractor_search'] = array(
    'info' => 'Contractor Search',
    'cache' => DRUPAL_NO_CACHE, // default
  ); 
    return $blocks;
  }
// /**
//  * Implements hook_block_view().
//  */
function com_gar_blocks_block_view($name) {
  if ($name == 'user_forum_posts') {
    $block = array(
      'subject' => t('User\'s Forum Posts'),
      'content' => user_forum_posts_content()
    );
  }
  if ($name == 'user_profile') {
    $block = array(
      'subject' => t('User\'s Profile'),
      'content' => user_profile_content()
    );
  }
  if ($name == 'contractor_search') {
    $block = array(
      'subject' => t(''),
      'content' => contractor_search_content(),
    );
  }

 
  return $block;
  
}

function user_forum_posts_content(){
  $content = false;
  $name = '';
  if(isset($_GET['name']) || preg_match('/user\/[0-9]+/', $_GET['q']) == 1){
    $uid = substr($_GET["q"], 5);
    $results = db_query("
      select n.nid, n.title, t.name, t.tid  from node n 
      join forum f on n.nid = f.nid
      join taxonomy_term_data t on t.tid = f.tid
      where uid =".$uid." and type = 'forum'


      ");
    

    foreach ($results as $key => $value) {
        $content = $content . '
      <a href="/?q=node/'.$value->{'nid'}.'">' .$value->{'title'}.'</a> in <a href="?q=forum/'.$value->{'tid'}.'">'.$value->{'name'}.'</a><br>';
    }
  }
  return $content;
}

function user_profile_content(){
  $content = false;
  $name = '';
  if(preg_match('/user\/[0-9]+/', $_GET['q']) == 1 ){
    $content = '
     
<p><strong>I provide bids through Architects and Engineers, work directly with home owners and offer design build services for residential projects.&nbsp; I welcome your inquiries on new construction or renovation projects involving:</strong><br />
<strong>Office Buildings&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Churches&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Industrial Warehouses&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Shopping Centers&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Restaurants&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Schools</strong><br />
<strong>Residential Additions&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Garages</strong><strong>&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Apartments&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Kitchens&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Bathrooms</strong><br />
<strong>Carpentry&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Cabinets&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Windows&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Tile&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Flooring&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Counter Tops&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Lighting</strong><br />
<strong>Exterior Repairs &amp; Upgrades&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Siding&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Decks &amp; Porches&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Roofing&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Concrete</strong><strong>&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Brick</strong><br />
<strong>S</strong><strong>tructural Repairs&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Underpinning&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Waterproofing&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Retaining Walls</strong><strong>&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Grading&nbsp;</strong><span class="style3">•</span>&nbsp;<strong>Drain Ti</strong><strong>le</strong></p>

<p><strong>Free estimate are provided to property owners.&nbsp; Estimates for residential work related to insurance claims or the purchase, sale or settlement of property are provided for a reasonable fee.</strong></p>

    ';
  }
  return $content;
}

function contractor_search_content(){
  $content = false;
  $result = db_query('
    SELECT distinct c.uid, u.name FROM comment c
    join users u on c.uid = u.uid
    ');
  if(preg_match('/node\/16/', $_GET['q']) == 1 ){
    $content = '
    <p><label>Search for contractor using keyword </label> <input id="keyword" placeholder="Keyword" type="text" /><button id="form-submit">Search</button></p>
    <script type="text/javascript">
      jQuery("#form-submit").click(function(){
        jQuery("#search-results").show()
        jQuery(".tag").text(jQuery("#keyword").val())
      })
    </script>
    <div id="search-results" style="display: none">';

    foreach ($result as $key => $value) {
      $stars = 4 - ($key % 2);
      $content = $content. '<div><a href="/?q=user/'.$value->{'uid'}.'">'.$value->{'name'}.'</a> <img alt="" src="sites/default/files/imgs/'.$stars.'stars.png" /><br />
      Specializes in:
      <ul>
        <li class="tag">&nbsp;</li>
        <li>General construction</li>
      </ul>
      </div>';
    }
    $content = $content.'</div>';
  }

return $content;
}
